-- V4: Idempotent alter to add country, address, gender and password_hash to app_user_profile

-- H2 / SQL Server compatible check using INFORMATION_SCHEMA.COLUMNS
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'APP_USER_PROFILE' AND COLUMN_NAME = 'COUNTRY'
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ADD COUNTRY VARCHAR(100);
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'APP_USER_PROFILE' AND COLUMN_NAME = 'ADDRESS'
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ADD ADDRESS VARCHAR(2000);
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'APP_USER_PROFILE' AND COLUMN_NAME = 'GENDER'
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ADD GENDER VARCHAR(50);
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'APP_USER_PROFILE' AND COLUMN_NAME = 'PASSWORD_HASH'
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ADD PASSWORD_HASH VARCHAR(255);
END

-- Make email NOT NULL if no NULLs exist
IF EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'APP_USER_PROFILE' AND COLUMN_NAME = 'EMAIL' AND IS_NULLABLE = 'YES'
)
AND NOT EXISTS (
  SELECT 1 FROM APP_USER_PROFILE WHERE EMAIL IS NULL
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ALTER COLUMN EMAIL VARCHAR(255) NOT NULL;
END

-- Add unique index/constraint on email if not exists (H2/SQL Server)
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
  JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
  WHERE tc.TABLE_NAME = 'APP_USER_PROFILE' AND tc.CONSTRAINT_TYPE = 'UNIQUE' AND ccu.COLUMN_NAME = 'EMAIL'
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ADD CONSTRAINT UQ_app_user_profile_email UNIQUE (EMAIL);
END

-- Make phone NOT NULL if no NULLs exist
IF EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'APP_USER_PROFILE' AND COLUMN_NAME = 'PHONE' AND IS_NULLABLE = 'YES'
)
AND NOT EXISTS (
  SELECT 1 FROM APP_USER_PROFILE WHERE PHONE IS NULL
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ALTER COLUMN PHONE VARCHAR(50) NOT NULL;
END

-- Add unique index/constraint on phone if not exists
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
  JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
  WHERE tc.TABLE_NAME = 'APP_USER_PROFILE' AND tc.CONSTRAINT_TYPE = 'UNIQUE' AND ccu.COLUMN_NAME = 'PHONE'
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ADD CONSTRAINT UQ_app_user_profile_phone UNIQUE (PHONE);
END
