-- V4: Idempotent alter to add country and address to app_user_profile (H2)

-- H2 doesn't support sys.columns, so use INFORMATION_SCHEMA.COLUMNS
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'APP_USER_PROFILE' AND COLUMN_NAME = 'COUNTRY'
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ADD COUNTRY VARCHAR(100);
END

IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'APP_USER_PROFILE' AND COLUMN_NAME = 'ADDRESS'
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ADD ADDRESS VARCHAR(2000);
END

