-- V5: Add module_id to user_feedback (H2)

-- Use INFORMATION_SCHEMA to check column existence
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'USER_FEEDBACK' AND COLUMN_NAME = 'MODULE_ID'
)
BEGIN
  ALTER TABLE USER_FEEDBACK ADD MODULE_ID VARCHAR(255);
END

-- Add FK in H2 (if module table exists)
-- H2 allows adding FK similarly
ALTER TABLE USER_FEEDBACK ADD CONSTRAINT FK_FEEDBACK_MODULE FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID);

