-- V6: Add questions (JSON/text) column to user_feedback (H2/active)
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'USER_FEEDBACK' AND COLUMN_NAME = 'QUESTIONS'
)
BEGIN
  ALTER TABLE USER_FEEDBACK ADD QUESTIONS VARCHAR(2000);
END

