-- V7: Add role column to app_user_profile (H2/active)
IF NOT EXISTS (
  SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'APP_USER_PROFILE' AND COLUMN_NAME = 'ROLE'
)
BEGIN
  ALTER TABLE APP_USER_PROFILE ADD ROLE VARCHAR(20) DEFAULT 'normal';
END

-- Ensure existing rows have default
UPDATE APP_USER_PROFILE SET ROLE = 'normal' WHERE ROLE IS NULL;

